### ISSUE TITLE
Player error float object cannot be interpreted as integer

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#20]
Code:
player = Player('277916')

**Traceback:**

Traceback (most recent call last):
  File "C:/Users/ehsan/PycharmProjects/ScrapPSLData/CreateCSV_AdvStats.py", line 9, in <module>
    print(Player('277916').name)
  File "C:\Users\ehsan\AppData\Roaming\Python\Python36\site-packages\espncricinfo\player.py", line 20, in __init__
    self.batting_fielding_averages = self._batting_fielding_averages()
  File "C:\Users\ehsan\AppData\Roaming\Python\Python36\site-packages\espncricinfo\player.py", line 79, in _batting_fielding_averages
    format_positions = [15*x for x in range(num_formats)]
TypeError: 'float' object cannot be interpreted as an integer

**Comment by dwillis** [comment]
@Ehsan1997 I haven't been able to reproduce this. Is this still happening for you?

**Comment by Ehsan1997** [comment]
It's working!
